// Chris Joakim, Microsoft, 2018/10/08

const express = require('express');
const router  = express.Router();

// The build_timestamp.json file is generated by Grunt
const build_timestamp_obj = require("../build_timestamp.json");


router.get('/ping', function(req, res) {
  var date = new Date();
  var obj = {};
  obj.date = date;
  obj.epoch = date.getTime();
  obj.build = build_timestamp_obj;
  res.json(obj);
});

module.exports = router;
